JSON dataset
      ↓
Load dataset
      ↓
Train / validation / test split
      ↓
Load tokenizer
      ↓
Load Qwen model
      ↓
Inspect chat template
      ↓
Format conversations
      ↓
Tokenization
      ↓
Inspect labels / loss masking
      ↓
LoRA
      ↓
SFT
      ↓
Evaluation

In [28]:
import torch
print(torch.cuda.is_available())
print(torch.cuda.get_device_name())

True
Tesla T4

In [29]:
import json
from collections import Counter

with open("/content/electronics_tutoring_dataset.json", "r") as file:
    data = json.load(file)

print(len(data))
print("Kirchhoff law number:",sum(row["topic"] == "Kirchhoff's Laws" for row in data))
print("diodes number:",sum(row["topic"] == "Diodes" for row in data))
print("BJTs number:",sum(row["topic"] == "BJTs" for row in data))
print("MOSFETs number:",sum(row["topic"] == "MOSFETs" for row in data))
print("Op-amps number:",sum(row["topic"] == "Op-amps" for row in data))
print(" ")


required = ["id","topic","difficulty","instruction","question","answer"]

count = 0
for item in data:
  for field in required:
    if not item.get(field):
      count += 1

print(count)

250
Kirchhoff law number: 51
diodes number: 50
BJTs number: 50
MOSFETs number: 50
Op-amps number: 49

0

In [30]:
from sklearn.model_selection import train_test_split

train, temp = train_test_split(data,test_size=0.2,random_state=0,shuffle=True)

valid, test = train_test_split(temp,test_size=0.5,random_state=0,shuffle=True)


print("Train:", len(train))
print("Valid:", len(valid))
print("Test:", len(test))

Train: 200
Valid: 25
Test: 25

In [31]:
print(train[0])

{'id': 72, 'topic': 'Diodes', 'difficulty': 'intermediate', 'instruction': 'Explain this concept as if you were tutoring an undergraduate engineering student.', 'question': 'Why does a diode conduct current in only one direction?', 'answer': "The PN junction's depletion region and built-in electric field oppose current flow in reverse bias by blocking majority carrier movement, while in forward bias the applied voltage overcomes this barrier and allows majority carriers to flow across the junction."}

In [32]:
from transformers import AutoModelForCausalLM, AutoTokenizer


checkpoint = "Qwen/Qwen2.5-1.5B-Instruct"

model = AutoModelForCausalLM.from_pretrained(checkpoint)
tokenizer = AutoTokenizer.from_pretrained(checkpoint)

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

In [33]:
model.num_parameters()

1543714304

In [34]:
from transformers import AutoConfig

config = AutoConfig.from_pretrained(checkpoint)

In [35]:
print(config)

Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151645,
  "hidden_act": "silu",
  "hidden_size": 1536,
  "initializer_range": 0.02,
  "intermediate_size": 8960,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 32768,
  "max_window_layers": 21,
  "model_type": "qwen2",
  "num_attention_heads": 12,
  "num_hidden_layers": 28,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.13.1",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

In [36]:
print("vocab size",len(tokenizer))
print("special tokens",tokenizer.special_tokens_map)
print("")
if tokenizer.chat_template:
  print(tokenizer.chat_template)

vocab size 151665
special tokens {'eos_token': '<|im_end|>', 'pad_token': '<|endoftext|>'}

{%- if tools %}
    {{- '<|im_start|>system\n' }}
    {%- if messages[0]['role'] == 'system' %}
        {{- messages[0]['content'] }}
    {%- else %}
        {{- 'You are Qwen, created by Alibaba Cloud. You are a helpful assistant.' }}
    {%- endif %}
    {{- "\n\n# Tools\n\nYou may call one or more functions to assist with the user query.\n\nYou are provided with function signatures within <tools></tools> XML tags:\n<tools>" }}
    {%- for tool in tools %}
        {{- "\n" }}
        {{- tool | tojson }}
    {%- endfor %}
    {{- "\n</tools>\n\nFor each function call, return a json object with function name and arguments within <tool_call></tool_call> XML tags:\n<tool_call>\n{\"name\": <function-name>, \"arguments\": <args-json-object>}\n</tool_call><|im_end|>\n" }}
{%- else %}
    {%- if messages[0]['role'] == 'system' %}
        {{- '<|im_start|>system\n' + messages[0]['content'] + '<|im_end|>\n' }}
    {%- else %}
        {{- '<|im_start|>system\nYou are Qwen, created by Alibaba Cloud. You are a helpful assistant.<|im_end|>\n' }}
    {%- endif %}
{%- endif %}
{%- for message in messages %}
    {%- if (message.role == "user") or (message.role == "system" and not loop.first) or (message.role == "assistant" and not message.tool_calls) %}
        {{- '<|im_start|>' + message.role + '\n' + message.content + '<|im_end|>' + '\n' }}
    {%- elif message.role == "assistant" %}
        {{- '<|im_start|>' + message.role }}
        {%- if message.content %}
            {{- '\n' + message.content }}
        {%- endif %}
        {%- for tool_call in message.tool_calls %}
            {%- if tool_call.function is defined %}
                {%- set tool_call = tool_call.function %}
            {%- endif %}
            {{- '\n<tool_call>\n{"name": "' }}
            {{- tool_call.name }}
            {{- '", "arguments": ' }}
            {{- tool_call.arguments | tojson }}
            {{- '}\n</tool_call>' }}
        {%- endfor %}
        {{- '<|im_end|>\n' }}
    {%- elif message.role == "tool" %}
        {%- if (loop.index0 == 0) or (messages[loop.index0 - 1].role != "tool") %}
            {{- '<|im_start|>user' }}
        {%- endif %}
        {{- '\n<tool_response>\n' }}
        {{- message.content }}
        {{- '\n</tool_response>' }}
        {%- if loop.last or (messages[loop.index0 + 1].role != "tool") %}
            {{- '<|im_end|>\n' }}
        {%- endif %}
    {%- endif %}
{%- endfor %}
{%- if add_generation_prompt %}
    {{- '<|im_start|>assistant\n' }}
{%- endif %}

In [37]:

text = train[0]
print(text)
instruction = text["instruction"]
question = text["question"]
answer = text["answer"]


messages = [
    {
        "role" : "system",
        "content" : instruction
    },
    {
        "role" : "user",
        "content":question,
    },
    {
        "role" : "assistant",
        "content":answer
    }
]

to_chat_template = tokenizer.apply_chat_template(messages,tokenize=False,add_generation_prompt = False)
print(to_chat_template)
print("")

tokenized_message = tokenizer(to_chat_template,add_special_tokens=False)["input_ids"]
print(tokenized_message)

decoded_message = tokenizer.decode(tokenized_message)
print(decoded_message)

{'id': 72, 'topic': 'Diodes', 'difficulty': 'intermediate', 'instruction': 'Explain this concept as if you were tutoring an undergraduate engineering student.', 'question': 'Why does a diode conduct current in only one direction?', 'answer': "The PN junction's depletion region and built-in electric field oppose current flow in reverse bias by blocking majority carrier movement, while in forward bias the applied voltage overcomes this barrier and allows majority carriers to flow across the junction."}
<|im_start|>system
Explain this concept as if you were tutoring an undergraduate engineering student.<|im_end|>
<|im_start|>user
Why does a diode conduct current in only one direction?<|im_end|>
<|im_start|>assistant
The PN junction's depletion region and built-in electric field oppose current flow in reverse bias by blocking majority carrier movement, while in forward bias the applied voltage overcomes this barrier and allows majority carriers to flow across the junction.<|im_end|>


[151644, 8948, 198, 840, 20772, 419, 7286, 438, 421, 498, 1033, 77043, 458, 40434, 14667, 5458, 13, 151645, 198, 151644, 872, 198, 10234, 1558, 264, 1853, 534, 6786, 1482, 304, 1172, 825, 5106, 30, 151645, 198, 151644, 77091, 198, 785, 61901, 48241, 594, 91848, 5537, 323, 5798, 3419, 9072, 2070, 33034, 1482, 6396, 304, 9931, 15470, 553, 22188, 8686, 18602, 7203, 11, 1393, 304, 4637, 15470, 279, 9251, 21720, 916, 6579, 419, 22103, 323, 6147, 8686, 34891, 311, 6396, 3941, 279, 48241, 13, 151645, 198]
<|im_start|>system
Explain this concept as if you were tutoring an undergraduate engineering student.<|im_end|>
<|im_start|>user
Why does a diode conduct current in only one direction?<|im_end|>
<|im_start|>assistant
The PN junction's depletion region and built-in electric field oppose current flow in reverse bias by blocking majority carrier movement, while in forward bias the applied voltage overcomes this barrier and allows majority carriers to flow across the junction.<|im_end|>

In [38]:
print(tokenizer("<|im_start|>assistant",add_special_tokens=False)["input_ids"])
print(tokenizer("<|im_end|>",add_special_tokens=False)["input_ids"])

[151644, 77091]
[151645]

In [39]:
tokens = tokenizer(to_chat_template,add_special_tokens=False)["input_ids"]
for i,token in enumerate(tokens):
  if(tokens[i] == 151644 and tokens[i+1] == 77091):
    start = i+2

for j in range(start,len(tokens)):
  if(tokens[j] == 151645):
    end = j

print(start)
print(end)

38
83

In [40]:
labels = tokenizer(to_chat_template,add_special_tokens=False)["input_ids"]

for i in range(0,start):
  labels[i] = -100

for j in range(end,len(labels)):
  labels[j] = -100

print(len(tokens))
print(len(labels))
print((tokens[34:84]))
print((labels[34:84]))

85
85
[151645, 198, 151644, 77091, 198, 785, 61901, 48241, 594, 91848, 5537, 323, 5798, 3419, 9072, 2070, 33034, 1482, 6396, 304, 9931, 15470, 553, 22188, 8686, 18602, 7203, 11, 1393, 304, 4637, 15470, 279, 9251, 21720, 916, 6579, 419, 22103, 323, 6147, 8686, 34891, 311, 6396, 3941, 279, 48241, 13, 151645]
[-100, -100, -100, -100, 198, 785, 61901, 48241, 594, 91848, 5537, 323, 5798, 3419, 9072, 2070, 33034, 1482, 6396, 304, 9931, 15470, 553, 22188, 8686, 18602, 7203, 11, 1393, 304, 4637, 15470, 279, 9251, 21720, 916, 6579, 419, 22103, 323, 6147, 8686, 34891, 311, 6396, 3941, 279, 48241, 13, -100]

In [41]:
print(model.named_parameters)

<bound method Module.named_parameters of Qwen2ForCausalLM(
  (model): Qwen2Model(
    (embed_tokens): Embedding(151936, 1536)
    (layers): ModuleList(
      (0-27): 28 x Qwen2DecoderLayer(
        (self_attn): Qwen2Attention(
          (q_proj): Linear(in_features=1536, out_features=1536, bias=True)
          (k_proj): Linear(in_features=1536, out_features=256, bias=True)
          (v_proj): Linear(in_features=1536, out_features=256, bias=True)
          (o_proj): Linear(in_features=1536, out_features=1536, bias=False)
        )
        (mlp): Qwen2MLP(
          (gate_proj): Linear(in_features=1536, out_features=8960, bias=False)
          (up_proj): Linear(in_features=1536, out_features=8960, bias=False)
          (down_proj): Linear(in_features=8960, out_features=1536, bias=False)
          (act_fn): SiLUActivation()
        )
        (input_layernorm): Qwen2RMSNorm((1536,), eps=1e-06)
        (post_attention_layernorm): Qwen2RMSNorm((1536,), eps=1e-06)
      )
    )
    (norm): Qwen2RMSNorm((1536,), eps=1e-06)
    (rotary_emb): Qwen2RotaryEmbedding()
  )
  (lm_head): Linear(in_features=1536, out_features=151936, bias=False)
)>

In [42]:
!pip install -U torchao

Requirement already satisfied: torchao in /usr/local/lib/python3.12/dist-packages (0.10.0)
Collecting torchao
  Downloading torchao-0.18.0-cp310-abi3-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (21 kB)
Downloading torchao-0.18.0-cp310-abi3-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (3.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 57.1 MB/s eta 0:00:00
Installing collected packages: torchao
  Attempting uninstall: torchao
    Found existing installation: torchao 0.10.0
    Uninstalling torchao-0.10.0:
      Successfully uninstalled torchao-0.10.0
Successfully installed torchao-0.18.0

In [43]:
from peft import get_peft_model,LoraConfig

peft_config = LoraConfig(
    target_modules = ["q_proj","v_proj"],
    task_type = "CAUSAL_LM",
    r = 8,
    lora_alpha = 16,
    lora_dropout= 0.05
)

peft_model = get_peft_model(model,peft_config)
peft_model.print_trainable_parameters()

WARNING:torchao:Failed to load /usr/local/lib/python3.12/dist-packages/torchao/_C_cutlass_90a.abi3.so: Could not load this library: /usr/local/lib/python3.12/dist-packages/torchao/_C_cutlass_90a.abi3.so
WARNING:torchao:Failed to load /usr/local/lib/python3.12/dist-packages/torchao/_C_mxfp8.cpython-310-x86_64-linux-gnu.so: Could not load this library: /usr/local/lib/python3.12/dist-packages/torchao/_C_mxfp8.cpython-310-x86_64-linux-gnu.so

trainable params: 1,089,536 || all params: 1,544,803,840 || trainable%: 0.0705

In [44]:
print(train)

[{'id': 72, 'topic': 'Diodes', 'difficulty': 'intermediate', 'instruction': 'Explain this concept as if you were tutoring an undergraduate engineering student.', 'question': 'Why does a diode conduct current in only one direction?', 'answer': "The PN junction's depletion region and built-in electric field oppose current flow in reverse bias by blocking majority carrier movement, while in forward bias the applied voltage overcomes this barrier and allows majority carriers to flow across the junction."}, {'id': 161, 'topic': 'MOSFETs', 'difficulty': 'basic', 'instruction': 'Give a clear conceptual explanation of the following electronics question.', 'question': 'What is the body effect in a MOSFET?', 'answer': 'The body effect is the change in threshold voltage that occurs when there is a voltage difference between the source and the body terminal, which effectively makes the threshold voltage a function of the source-body voltage rather than a fixed constant.'}, {'id': 181, 'topic': 'MOSFETs', 'difficulty': 'intermediate', 'instruction': 'Give a clear conceptual explanation of the following electronics question.', 'question': 'Why is the substrate (body) terminal of an NMOS transistor typically connected to the most negative supply voltage in a circuit?', 'answer': 'Connecting the body to the most negative potential ensures that the body-to-source and body-to-drain junctions remain reverse biased across all normal operating conditions, preventing unwanted forward conduction through those parasitic diode junctions.'}, {'id': 76, 'topic': 'Diodes', 'difficulty': 'intermediate', 'instruction': 'Give a clear conceptual explanation of the following electronics question.', 'question': 'Why does a diode have a nonzero turn-on voltage instead of conducting at any positive voltage?', 'answer': "The built-in potential from the depletion region's electric field must be overcome before current can flow significantly, so a minimum forward voltage is required to reduce the barrier enough for diffusion current to dominate."}, {'id': 60, 'topic': 'Diodes', 'difficulty': 'basic', 'instruction': 'Explain this electronics concept to an undergraduate student.', 'question': 'What is a Zener diode?', 'answer': 'A Zener diode is a specially designed diode that is operated in reverse breakdown to maintain a constant voltage across it, making it useful for voltage regulation applications.'}, {'id': 102, 'topic': 'BJTs', 'difficulty': 'basic', 'instruction': 'Explain this concept as if you were tutoring an undergraduate engineering student.', 'question': 'What is a BJT?', 'answer': 'A BJT (Bipolar Junction Transistor) is a three-terminal semiconductor device made of two PN junctions arranged as either NPN or PNP, used for amplification and switching. Its terminals are the base, emitter, and collector.'}, {'id': 230, 'topic': 'Op-amps', 'difficulty': 'intermediate', 'instruction': 'Explain this electronics concept to an undergraduate student.', 'question': 'Why is high common-mode rejection important in a difference amplifier used to measure small signals in noisy environments?', 'answer': "If a small desired signal, like a sensor's output, is riding on top of a much larger noise voltage common to both input lines, high common-mode rejection ensures the amplifier suppresses that shared noise while still faithfully amplifying the actual difference signal, which is what a difference amplifier is designed to extract."}, {'id': 19, 'topic': "Kirchhoff's Laws", 'difficulty': 'basic', 'instruction': 'Answer the following electronics question in a way an undergraduate would understand.', 'question': 'What is a reference node (ground) used for in nodal analysis?', 'answer': 'The reference node is assigned a voltage of 0 V and serves as the baseline against which all other node voltages are measured, which reduces the number of unknowns you need to solve for.'}, {'id': 189, 'topic': 'MOSFETs', 'difficulty': 'intermediate', 'instruction': 'Answer the following electronics question in a way an undergraduate would understand.', 'question': 'Why does a MOSFET need a gate driver circuit in high-power switching applications?', 'answer': 'The gate capacitance must be charged and discharged quickly to achieve fast switching, which requires more current than typical logic-level outputs can supply, so a dedicated gate driver circuit provides the higher current needed for fast, clean transitions.'}, {'id': 16, 'topic': "Kirchhoff's Laws", 'difficulty': 'basic', 'instruction': 'Give a clear conceptual explanation of the following electronics question.', 'question': 'What is mesh analysis?', 'answer': 'Mesh analysis is a systematic method for solving planar circuits by writing KVL equations around each independent loop (mesh) in terms of unknown mesh currents, then solving the resulting system of equations.'}, {'id': 218, 'topic': 'Op-amps', 'difficulty': 'basic', 'instruction': 'Provide a concise technical explanation suitable for an electronics student.', 'question': "What does it mean for an op-amp's output to be 'saturated' or 'railed'?", 'answer': "An op-amp's output is saturated or railed when it reaches its maximum or minimum possible output voltage, typically close to its positive or negative supply voltage, and can no longer increase or decrease further even if the input demands it."}, {'id': 75, 'topic': 'Diodes', 'difficulty': 'intermediate', 'instruction': 'Explain this electronics concept to an undergraduate student.', 'question': 'Why is there a small reverse leakage current even in reverse bias?', 'answer': 'Minority carriers (electrons in the p-side, holes in the n-side) are still thermally generated and can be swept across the junction by the reverse electric field, producing a small saturation current that exists regardless of bias magnitude until breakdown.'}, {'id': 8, 'topic': "Kirchhoff's Laws", 'difficulty': 'basic', 'instruction': 'Provide a concise technical explanation suitable for an electronics student.', 'question': 'Define KVL in one sentence.', 'answer': 'KVL states that the sum of voltage drops and rises around any closed loop equals zero.'}, {'id': 228, 'topic': 'Op-amps', 'difficulty': 'intermediate', 'instruction': 'Provide a concise technical explanation suitable for an electronics student.', 'question': "Why does slew rate limit an op-amp's performance for large, fast-changing signals even if its bandwidth would otherwise be sufficient?", 'answer': 'Slew rate is a large-signal limitation caused by the maximum current available to charge internal compensation capacitors, so even if small-signal bandwidth theoretically supports a certain frequency, a large-amplitude fast-changing signal can still be limited to a fixed maximum voltage-change rate, causing distorted, ramp-like output instead of a faithful reproduction.'}, {'id': 182, 'topic': 'MOSFETs', 'difficulty': 'intermediate', 'instruction': 'Explain this concept as if you were tutoring an undergraduate engineering student.', 'question': 'Why do MOSFETs generally have faster switching speeds than BJTs in many applications?', 'answer': 'MOSFETs are majority-carrier devices controlled by an electric field, avoiding the minority-carrier storage and removal delays that limit BJT switching, though very high gate capacitance in large power MOSFETs can still limit speed if not driven with sufficient current.'}, {'id': 229, 'topic': 'Op-amps', 'difficulty': 'intermediate', 'instruction': 'Answer the following electronics question in a way an undergraduate would understand.', 'question': 'Why do real op-amps have a nonzero offset voltage while ideal op-amps assume zero?', 'answer': 'Real op-amps are built from transistors that can never be perfectly matched due to manufacturing variation, so a small inherent voltage difference is needed at the input to bring the output to zero, unlike the idealized model, which assumes perfectly symmetric internal components.'}, {'id': 34, 'topic': "Kirchhoff's Laws", 'difficulty': 'intermediate', 'instruction': 'Answer the following electronics question in a way an undergraduate would understand.', 'question': "Why is KVL considered a consequence of Maxwell's equations rather than an independent law?", 'answer': "KVL follows from Faraday's law under the assumption of negligible time-varying magnetic flux through the loop, which holds for lumped circuits at low frequencies. It is an approximation of the more general electromagnetic behavior."}, {'id': 203, 'topic': 'Op-amps', 'difficulty': 'basic', 'instruction': 'Provide a concise technical explanation suitable for an electronics student.', 'question': 'What are the two input terminals of an op-amp called?', 'answer': 'The two input terminals of an op-amp are called the inverting input (marked with a minus sign) and the non-inverting input (marked with a plus sign).'}, {'id': 126, 'topic': 'BJTs', 'difficulty': 'intermediate', 'instruction': 'Give a clear conceptual explanation of the following electronics question.', 'question': 'Why is emitter current always greater than collector current in a BJT?', 'answer': 'Some of the carriers injected by the emitter recombine within the base region and never reach the collector, so the collector current is always slightly less than the emitter current, with the difference approximately equal to the base current.'}, {'id': 225, 'topic': 'Op-amps', 'difficulty': 'intermediate', 'instruction': 'Explain this electronics concept to an undergraduate student.', 'question': 'Why does the inverting amplifier configuration produce an output that is 180 degrees out of phase with the input?', 'answer': 'In the inverting configuration, the non-inverting input is grounded, so the virtual short forces the inverting input to also sit near 0 V; as input current flows through the input resistor toward this virtual ground, the feedback resistor must carry an equal but oppositely directed current to maintain that virtual ground, which requires the output to swing in the opposite direction from the input.'}, {'id': 241, 'topic': 'Op-amps', 'difficulty': 'applied', 'instruction': 'Give a clear conceptual explanation of the following electronics question.', 'question': 'A non-inverting amplifier has Rf = 9 kOhm and Rin = 1 kOhm. What is its gain?', 'answer': 'Using the non-inverting gain formula, gain = 1 + (Rf/Rin) = 1 + (9 kOhm / 1 kOhm) = 1 + 9 = 10.'}, {'id': 211, 'topic': 'Op-amps', 'difficulty': 'basic', 'instruction': 'Give a clear conceptual explanation of the following electronics question.', 'question': 'What is a summing amplifier?', 'answer': 'A summing amplifier is an op-amp circuit, typically in the inverting configuration, that produces an output proportional to the weighted sum of multiple input voltages, each scaled by its own input resistor.'}, {'id': 171, 'topic': 'MOSFETs', 'difficulty': 'basic', 'instruction': 'Give a clear conceptual explanation of the following electronics question.', 'question': 'What is the drain terminal of a MOSFET?', 'answer': "The drain terminal is the terminal where majority carriers exit the channel after flowing through it, and it's typically at a higher potential than the source for an NMOS device operating normally."}, {'id': 17, 'topic': "Kirchhoff's Laws", 'difficulty': 'basic', 'instruction': 'Explain this concept as if you were tutoring an undergraduate engineering student.', 'question': 'Explain KCL briefly.', 'answer': "KCL says that current can't pile up at a node - whatever flows in must flow back out, because charge is conserved."}, {'id': 147, 'topic': 'BJTs', 'difficulty': 'applied', 'instruction': 'Explain this concept as if you were tutoring an undergraduate engineering student.', 'question': 'Explain with an example how an emitter follower can be used as a buffer between a high-impedance source and a low-impedance load.', 'answer': "Suppose a sensor has high output impedance and needs to drive a low-impedance speaker. Connecting the sensor to the base of an emitter-follower BJT allows the high input impedance at the base to avoid loading down the sensor, while the low output impedance at the emitter can efficiently drive the low-impedance speaker, preserving the signal's voltage level."}, {'id': 107, 'topic': 'BJTs', 'difficulty': 'basic', 'instruction': 'Explain this concept as if you were tutoring an undergraduate engineering student.', 'question': 'What is the saturation region of a BJT?', 'answer': 'The saturation region is the operating mode where both junctions are forward biased, and the transistor behaves like a closed switch with a small, roughly constant voltage between collector and emitter.'}, {'id': 244, 'topic': 'Op-amps', 'difficulty': 'applied', 'instruction': 'Answer the following electronics question in a way an undergraduate would understand.', 'question': 'Compare the inverting and non-inverting amplifier configurations in terms of input impedance.', 'answer': "The non-inverting configuration has very high input impedance because the signal connects directly to the op-amp's non-inverting input, which ideally draws no current. The inverting configuration has input impedance approximately equal to the input resistor value, since the signal source must drive current through that resistor toward the virtual ground, making it comparatively lower."}, {'id': 5, 'topic': "Kirchhoff's Laws", 'difficulty': 'basic', 'instruction': 'Explain this electronics concept to an undergraduate student.', 'question': 'What physical law is KCL based on?', 'answer': 'KCL is based on the conservation of electric charge. Since charge cannot be created or destroyed at a node, whatever current flows in must flow back out.'}, {'id': 220, 'topic': 'Op-amps', 'difficulty': 'basic', 'instruction': 'Explain this electronics concept to an undergraduate student.', 'question': 'Explain an op-amp briefly.', 'answer': 'An op-amp is a high-gain amplifier building block that, combined with feedback components, can be configured to perform tasks like amplification, summing, integration, and comparison.'}, {'id': 62, 'topic': 'Diodes', 'difficulty': 'basic', 'instruction': 'Explain this concept as if you were tutoring an undergraduate engineering student.', 'question': 'What is a photodiode?', 'answer': 'A photodiode is a diode designed to generate current when exposed to light, operated in reverse bias so that absorbed photons create electron-hole pairs that contribute to a measurable photocurrent.'}, {'id': 125, 'topic': 'BJTs', 'difficulty': 'intermediate', 'instruction': 'Explain this electronics concept to an undergraduate student.', 'question': 'Why does collector current increase slightly with collector-emitter voltage in the active region (Early effect)?', 'answer': 'As collector-emitter voltage increases, the base-collector depletion region widens, effectively narrowing the neutral base width, which reduces recombination and allows more injected carriers to reach the collector, slightly increasing collector current.'}, {'id': 53, 'topic': 'Diodes', 'difficulty': 'basic', 'instruction': 'Provide a concise technical explanation suitable for an electronics student.', 'question': 'What is a PN junction?', 'answer': 'A PN junction is the boundary formed where p-type semiconductor (with excess holes) meets n-type semiconductor (with excess electrons). This junction is the basic building block of a diode and creates a region that controls current flow.'}, {'id': 67, 'topic': 'Diodes', 'difficulty': 'basic', 'instruction': 'Explain this concept as if you were tutoring an undergraduate engineering student.', 'question': "What is a diode's static resistance?", 'answer': "Static resistance is the ratio of DC voltage to DC current at a specific operating point on the diode's characteristic curve, which is not constant because diode behavior is nonlinear."}, {'id': 27, 'topic': "Kirchhoff's Laws", 'difficulty': 'intermediate', 'instruction': 'Explain this concept as if you were tutoring an undergraduate engineering student.', 'question': "Why can KCL be written either as 'sum of currents in equals sum out' or as 'algebraic sum of currents equals zero'?", 'answer': "These are the same statement written two ways. If you define current entering as positive and current leaving as negative, then 'in equals out' becomes 'positive terms plus negative terms equal zero', which is the algebraic sum form."}, {'id': 110, 'topic': 'BJTs', 'difficulty': 'basic', 'instruction': 'Explain this electronics concept to an undergraduate student.', 'question': 'What is the common-emitter configuration?', 'answer': 'The common-emitter configuration uses the emitter as the shared reference terminal, with input applied at the base and output taken at the collector, and is the most common configuration for voltage amplification.'}, {'id': 242, 'topic': 'Op-amps', 'difficulty': 'applied', 'instruction': 'Explain this concept as if you were tutoring an undergraduate engineering student.', 'question': 'An inverting amplifier has Rf = 20 kOhm and Rin = 4 kOhm, with a 0.5 V input signal. What is the output voltage?', 'answer': 'Using the inverting gain formula, gain = -(Rf/Rin) = -(20 kOhm / 4 kOhm) = -5. The output voltage is gain x input = -5 x 0.5 V = -2.5 V.'}, {'id': 223, 'topic': 'Op-amps', 'difficulty': 'intermediate', 'instruction': 'Provide a concise technical explanation suitable for an electronics student.', 'question': "Why does the virtual short concept hold even though no current flows between the op-amp's inputs?", 'answer': 'With negative feedback in place and very high open-loop gain, any nonzero voltage difference between the inputs would be amplified enormously and drive the output to correct itself through the feedback path, so in a stable operating condition the input difference settles extremely close to zero, even though this is enforced by the feedback loop rather than by any direct current path between the inputs.'}, {'id': 41, 'topic': "Kirchhoff's Laws", 'difficulty': 'intermediate', 'instruction': 'Give a clear conceptual explanation of the following electronics question.', 'question': 'Why is it important to track the direction of traversal when writing a KVL equation?', 'answer': "The traversal direction determines whether you record a component's voltage as a rise or a drop, and if the direction is switched partway through the loop without adjusting the signs, the equation will no longer represent a physically closed path."}, {'id': 14, 'topic': "Kirchhoff's Laws", 'difficulty': 'basic', 'instruction': 'Answer the following electronics question in a way an undergraduate would understand.', 'question': 'What is a branch in circuit analysis?', 'answer': 'A branch is a single circuit element, such as a resistor or source, connecting two nodes. KCL and KVL equations are written in terms of the currents and voltages associated with branches.'}, {'id': 4, 'topic': "Kirchhoff's Laws", 'difficulty': 'basic', 'instruction': 'Answer the following electronics question in a way an undergraduate would understand.', 'question': "What does 'loop' mean in the context of KVL?", 'answer': 'A loop is any closed path in a circuit that starts and ends at the same point, passing through a series of circuit elements. KVL applies to any such loop, regardless of how many elements it contains.'}, {'id': 245, 'topic': 'Op-amps', 'difficulty': 'applied', 'instruction': 'Explain this electronics concept to an undergraduate student.', 'question': "What happens to a comparator's output when the voltage at its non-inverting input rises above the voltage at its inverting input?", 'answer': 'The output rapidly swings toward its positive supply rail because the open-loop gain amplifies the now-positive input difference to its maximum, saturating the output high until the input condition reverses.'}, {'id': 25, 'topic': "Kirchhoff's Laws", 'difficulty': 'intermediate', 'instruction': 'Explain this electronics concept to an undergraduate student.', 'question': 'Why is KCL appli

In [45]:
messages_train = []

for text in train:
  instruction = text["instruction"]
  question = text["question"]
  answer = text["answer"]
  messages_train.append([
        {
            "role" : "system",
            "content" : instruction
        },
        {
            "role" : "user",
            "content":question,
        },
        {
            "role" : "assistant",
            "content":answer
        }
    ])

In [46]:
print(len(messages_train))
print(messages_train[0])

200
[{'role': 'system', 'content': 'Explain this concept as if you were tutoring an undergraduate engineering student.'}, {'role': 'user', 'content': 'Why does a diode conduct current in only one direction?'}, {'role': 'assistant', 'content': "The PN junction's depletion region and built-in electric field oppose current flow in reverse bias by blocking majority carrier movement, while in forward bias the applied voltage overcomes this barrier and allows majority carriers to flow across the junction."}]

In [47]:
messages_validation = []

for text in valid:
  instruction = text["instruction"]
  question = text["question"]
  answer = text["answer"]
  messages_validation.append([
        {
            "role" : "system",
            "content" : instruction
        },
        {
            "role" : "user",
            "content":question,
        },
        {
            "role" : "assistant",
            "content":answer
        }
    ])

In [48]:
print(len(messages_validation))
print(messages_validation[0])

25
[{'role': 'system', 'content': 'Explain this concept as if you were tutoring an undergraduate engineering student.'}, {'role': 'user', 'content': "Why doesn't a MOSFET's gate draw significant current in steady state?"}, {'role': 'assistant', 'content': 'The gate is separated from the channel by a thin insulating oxide layer, so no DC current can flow into the gate; the gate voltage instead controls the channel through an electric field.'}]

In [49]:
from datasets import Dataset

# Convert each conversation into {"messages": [...]}
train_data = [{"messages": conversation} for conversation in messages_train]

train_dataset = Dataset.from_list(train_data)

print(len(train_dataset))
print(train_dataset[0])

200
{'messages': [{'content': 'Explain this concept as if you were tutoring an undergraduate engineering student.', 'role': 'system'}, {'content': 'Why does a diode conduct current in only one direction?', 'role': 'user'}, {'content': "The PN junction's depletion region and built-in electric field oppose current flow in reverse bias by blocking majority carrier movement, while in forward bias the applied voltage overcomes this barrier and allows majority carriers to flow across the junction.", 'role': 'assistant'}]}

In [50]:
valid_data = [{"messages": conversation} for conversation in messages_validation]

valid_dataset = Dataset.from_list(valid_data)

print(len(valid_dataset))
print(valid_dataset[0])

25
{'messages': [{'content': 'Explain this concept as if you were tutoring an undergraduate engineering student.', 'role': 'system'}, {'content': "Why doesn't a MOSFET's gate draw significant current in steady state?", 'role': 'user'}, {'content': 'The gate is separated from the channel by a thin insulating oxide layer, so no DC current can flow into the gate; the gate voltage instead controls the channel through an electric field.', 'role': 'assistant'}]}

In [51]:
!pip install -U trl

Requirement already satisfied: trl in /usr/local/lib/python3.12/dist-packages (1.10.0)
Requirement already satisfied: accelerate>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from trl) (1.14.0)
Requirement already satisfied: datasets>=4.7.0 in /usr/local/lib/python3.12/dist-packages (from trl) (5.0.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from trl) (3.1.6)
Requirement already satisfied: packaging>20.0 in /usr/local/lib/python3.12/dist-packages (from trl) (26.2)
Requirement already satisfied: transformers>=4.56.2 in /usr/local/lib/python3.12/dist-packages (from trl) (5.13.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl) (2.0.2)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl) (6.0.3)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl) (2.11.0+cu128)
Requirement already satisfied: huggingface_hub>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl) (1.23.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl) (0.8.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (3.29.7)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (25.0.1)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (3.8.1)
Requirement already satisfied: multiprocess<0.70.20 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (0.70.16)
Requirement already satisfied: fsspec<=2026.6.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.6.0,>=2023.1.0->datasets>=4.7.0->trl) (2025.3.0)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.56.2->trl) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.56.2->trl) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers>=4.56.2->trl) (0.26.8)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->trl) (3.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.6.0,>=2023.1.0->datasets>=4.7.0->trl) (3.14.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=4.7.0->trl) (4.14.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=4.7.0->trl) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=4.7.0->trl) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=4.7.0->trl) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets>=4.7.0->trl) (0.16.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (8.4.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (1.5.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (4.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets>=4.7.0->trl) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets>=4.7.0->trl) (2.5.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (3.6.1)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (12.9.7)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (12.8.90)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=4.7.0->trl) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=4.7.0->trl) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=4.7.0->trl) (2026.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers>=4.56.2->trl) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers>=4.56.2->trl) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers>=4.56.2->trl) (0.0.4)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets>=4.7.0->trl) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets>=4.7.0->trl) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets>=4.7.0->trl) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets>=4.7.0->trl) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets>=4.7.0->trl) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets>=4.7.0->trl) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets>=4.7.0->trl) (1.24.2)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings<13,>=12.9.4->torch>=2.0.0->accelerate>=1.4.0->trl) (1.5.6)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets>=4.7.0->trl) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers>=4.56.2->trl) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers>=4.56.2->trl) (2.20.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate>=1.4.0->trl) (1.3.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers>=4.56.2->trl) (0.1.2)

In [52]:
import trl
print(trl.__version__)

1.10.0

In [53]:
print(tokenizer.chat_template)

{%- if tools %}
    {{- '<|im_start|>system\n' }}
    {%- if messages[0]['role'] == 'system' %}
        {{- messages[0]['content'] }}
    {%- else %}
        {{- 'You are Qwen, created by Alibaba Cloud. You are a helpful assistant.' }}
    {%- endif %}
    {{- "\n\n# Tools\n\nYou may call one or more functions to assist with the user query.\n\nYou are provided with function signatures within <tools></tools> XML tags:\n<tools>" }}
    {%- for tool in tools %}
        {{- "\n" }}
        {{- tool | tojson }}
    {%- endfor %}
    {{- "\n</tools>\n\nFor each function call, return a json object with function name and arguments within <tool_call></tool_call> XML tags:\n<tool_call>\n{\"name\": <function-name>, \"arguments\": <args-json-object>}\n</tool_call><|im_end|>\n" }}
{%- else %}
    {%- if messages[0]['role'] == 'system' %}
        {{- '<|im_start|>system\n' + messages[0]['content'] + '<|im_end|>\n' }}
    {%- else %}
        {{- '<|im_start|>system\nYou are Qwen, created by Alibaba Cloud. You are a helpful assistant.<|im_end|>\n' }}
    {%- endif %}
{%- endif %}
{%- for message in messages %}
    {%- if (message.role == "user") or (message.role == "system" and not loop.first) or (message.role == "assistant" and not message.tool_calls) %}
        {{- '<|im_start|>' + message.role + '\n' + message.content + '<|im_end|>' + '\n' }}
    {%- elif message.role == "assistant" %}
        {{- '<|im_start|>' + message.role }}
        {%- if message.content %}
            {{- '\n' + message.content }}
        {%- endif %}
        {%- for tool_call in message.tool_calls %}
            {%- if tool_call.function is defined %}
                {%- set tool_call = tool_call.function %}
            {%- endif %}
            {{- '\n<tool_call>\n{"name": "' }}
            {{- tool_call.name }}
            {{- '", "arguments": ' }}
            {{- tool_call.arguments | tojson }}
            {{- '}\n</tool_call>' }}
        {%- endfor %}
        {{- '<|im_end|>\n' }}
    {%- elif message.role == "tool" %}
        {%- if (loop.index0 == 0) or (messages[loop.index0 - 1].role != "tool") %}
            {{- '<|im_start|>user' }}
        {%- endif %}
        {{- '\n<tool_response>\n' }}
        {{- message.content }}
        {{- '\n</tool_response>' }}
        {%- if loop.last or (messages[loop.index0 + 1].role != "tool") %}
            {{- '<|im_end|>\n' }}
        {%- endif %}
    {%- endif %}
{%- endfor %}
{%- if add_generation_prompt %}
    {{- '<|im_start|>assistant\n' }}
{%- endif %}

In [54]:
from trl import SFTConfig,SFTTrainer

sft_config = SFTConfig(
    output_dir="./results",

    # Training
    num_train_epochs=3,
    per_device_train_batch_size=2,
    gradient_accumulation_steps=4,
    learning_rate=2e-4,

    # Sequence length
    max_length=512,

    # Evaluation
    eval_strategy="epoch",

    # Saving
    save_strategy="epoch",

    # Train only on assistant responses
    assistant_only_loss=True,

    # Optional
    logging_steps=10,
    report_to="none",
)

trainer = SFTTrainer(model=peft_model,args=sft_config,train_dataset=train_dataset,eval_dataset=valid_dataset)

trainer.train()

Tokenizing train dataset:   0%|          | 0/200 [00:00<?, ? examples/s]

Building labels for train dataset:   0%|          | 0/200 [00:00<?, ? examples/s]

Truncating train dataset:   0%|          | 0/200 [00:00<?, ? examples/s]

Dropping fully masked examples from train dataset:   0%|          | 0/200 [00:00<?, ? examples/s]

Tokenizing eval dataset:   0%|          | 0/25 [00:00<?, ? examples/s]

Building labels for eval dataset:   0%|          | 0/25 [00:00<?, ? examples/s]

Truncating eval dataset:   0%|          | 0/25 [00:00<?, ? examples/s]

Dropping fully masked examples from eval dataset:   0%|          | 0/25 [00:00<?, ? examples/s]

[transformers] The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None, 'pad_token_id': 151643}.

TrainOutput(global_step=75, training_loss=1.6062900479634603, metrics={'train_runtime': 335.1806, 'train_samples_per_second': 1.79, 'train_steps_per_second': 0.224, 'total_flos': 486498617659392.0, 'train_loss': 1.6062900479634603, 'epoch': 3.0})

In [55]:
print(trainer.model)

PeftModelForCausalLM(
  (base_model): LoraModel(
    (model): Qwen2ForCausalLM(
      (model): Qwen2Model(
        (embed_tokens): Embedding(151936, 1536)
        (layers): ModuleList(
          (0-27): 28 x Qwen2DecoderLayer(
            (self_attn): Qwen2Attention(
              (q_proj): lora.Linear(
                (base_layer): Linear(in_features=1536, out_features=1536, bias=True)
                (lora_dropout): ModuleDict(
                  (default): Dropout(p=0.05, inplace=False)
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=1536, out_features=8, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=8, out_features=1536, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (k_proj): Linear(in_features=1536, out_features=256, bias=True)
              (v_proj): lora.Linear(
                (base_layer): Linear(in_features=1536, out_features=256, bias=True)
                (lora_dropout): ModuleDict(
                  (default): Dropout(p=0.05, inplace=False)
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=1536, out_features=8, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=8, out_features=256, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (o_proj): Linear(in_features=1536, out_features=1536, bias=False)
            )
            (mlp): Qwen2MLP(
              (gate_proj): Linear(in_features=1536, out_features=8960, bias=False)
              (up_proj): Linear(in_features=1536, out_features=8960, bias=False)
              (down_proj): Linear(in_features=8960, out_features=1536, bias=False)
              (act_fn): SiLUActivation()
            )
            (input_layernorm): Qwen2RMSNorm((1536,), eps=1e-06)
            (post_attention_layernorm): Qwen2RMSNorm((1536,), eps=1e-06)
          )
        )
        (norm): Qwen2RMSNorm((1536,), eps=1e-06)
        (rotary_emb): Qwen2RotaryEmbedding()
      )
      (lm_head): Linear(in_features=1536, out_features=151936, bias=False)
    )
  )
)

In [56]:
trainer.save_model("./electronics-lora")
tokenizer.save_pretrained("./electronics-lora")

('./electronics-lora/tokenizer_config.json',
 './electronics-lora/chat_template.jinja',
 './electronics-lora/tokenizer.json')

In [57]:
import os

print(os.listdir("./electronics-lora"))

['README.md', 'adapter_model.safetensors', 'training_args.bin', 'chat_template.jinja', 'tokenizer_config.json', 'adapter_config.json', 'tokenizer.json']

Evaluation

A)Base Model (Qwen2.5-1.5B-Instruct)

B) Fine-tuned model (Qwen2.5-1.5B-Instruct + LoRA)

In [58]:
messages_test = []

for text in test:
  instruction = text["instruction"]
  question = text["question"]
  answer = text["answer"]
  messages_test.append([
        {
            "role" : "system",
            "content" : instruction
        },
        {
            "role" : "user",
            "content":question,
        },
        {
            "role" : "assistant",
            "content":answer
        }
    ])

from datasets import Dataset

# Convert each conversation into {"messages": [...]}
test_data = [{"messages": conversation} for conversation in messages_test]

test_data = Dataset.from_list(test_data)

print(len(test_data))
print(test_data[0])

25
{'messages': [{'content': 'Explain this electronics concept to an undergraduate student.', 'role': 'system'}, {'content': "What happens to a MOSFET's drain current if the drain-source voltage is increased well beyond the overdrive voltage while gate-source voltage stays fixed?", 'role': 'user'}, {'content': 'Once the transistor is in saturation, further increases in drain-source voltage have only a small effect on drain current (due to channel-length modulation), so the current stays approximately constant rather than continuing to rise proportionally.', 'role': 'assistant'}]}

In [59]:
test_sample1 = test_data[0]

instruction = test_sample1["messages"][0]["content"]
question = test_sample1["messages"][1]["content"]
reference_answer = test_sample1["messages"][2]["content"]

print("INSTRUCTION:")
print(instruction)

print("\nQUESTION:")
print(question)

print("\nREFERENCE ANSWER:")
print(reference_answer)

INSTRUCTION:
Explain this electronics concept to an undergraduate student.

QUESTION:
What happens to a MOSFET's drain current if the drain-source voltage is increased well beyond the overdrive voltage while gate-source voltage stays fixed?

REFERENCE ANSWER:
Once the transistor is in saturation, further increases in drain-source voltage have only a small effect on drain current (due to channel-length modulation), so the current stays approximately constant rather than continuing to rise proportionally.

In [60]:
conversation = [
    {
        "role": "system",
        "content": instruction
    },
    {
        "role": "user",
        "content": question
    }
]

In [61]:
prompt = tokenizer.apply_chat_template(conversation,tokenize=False,add_generation_prompt=True)
print(prompt)

<|im_start|>system
Explain this electronics concept to an undergraduate student.<|im_end|>
<|im_start|>user
What happens to a MOSFET's drain current if the drain-source voltage is increased well beyond the overdrive voltage while gate-source voltage stays fixed?<|im_end|>
<|im_start|>assistant

In [62]:
inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

outputs = peft_model.generate(
    **inputs,
    max_new_tokens=256,
    do_sample=False
)

generated = tokenizer.decode(
    outputs[0][inputs["input_ids"].shape[1]:],
    skip_special_tokens=True
)

print("MODEL ANSWER:")
print(generated)

print("\nREFERENCE ANSWER:")
print(reference_answer)

MODEL ANSWER:
The drain current increases exponentially as long as it remains below the breakdown voltage, but once that threshold is exceeded, the device will be damaged and may fail catastrophically.

REFERENCE ANSWER:
Once the transistor is in saturation, further increases in drain-source voltage have only a small effect on drain current (due to channel-length modulation), so the current stays approximately constant rather than continuing to rise proportionally.

In [63]:
checkpoint = "Qwen/Qwen2.5-1.5B-Instruct"

base_model = AutoModelForCausalLM.from_pretrained(checkpoint)
base_tokenizer = AutoTokenizer.from_pretrained(checkpoint)

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

In [64]:
inputs = base_tokenizer(prompt, return_tensors="pt").to(base_model.device)

outputs = base_model.generate(
    **inputs,
    max_new_tokens=256,
    do_sample=False
)

generated = base_tokenizer.decode(
    outputs[0][inputs["input_ids"].shape[1]:],
    skip_special_tokens=True
)

print("MODEL ANSWER:")
print(generated)

print("\nREFERENCE ANSWER:")
print(reference_answer)

MODEL ANSWER:
When you increase the drain-source voltage (VDS) of a MOSFET past its overdrive voltage, several things happen:

1. **Threshold Voltage Increase**: The threshold voltage (VT), which is the minimum gate-to-source voltage required for the device to start conducting, increases. This means that it takes more positive gate voltage to turn on the MOSFET.

2. **Drain Current Increase**: As VDS increases further, the drain current (ID) also increases. However, there are practical limits to how much ID can be sustained before other factors come into play such as saturation region behavior or thermal considerations.

3. **Saturation Region**: Beyond a certain point, the drain current starts to saturate, meaning it approaches a maximum value determined by the material properties and geometry of the MOSFET. At this point, increasing VDS no longer significantly increases ID.

4. **Power Dissipation**: If the power dissipated in the MOSFET exceeds its rated power capability, it will eventually fail due to overheating.

5. **Gate-Source Voltage Impact**: While the question specifies keeping the gate-source voltage constant, note that changes in VGS can affect the performance and efficiency of the MOSFET. For instance, a higher VGS might reduce

REFERENCE ANSWER:
Once the transistor is in saturation, further increases in drain-source voltage have only a small effect on drain current (due to channel-length modulation), so the current stays approximately constant rather than continuing to rise proportionally.

In [65]:
print(test[0])

{'id': 195, 'topic': 'MOSFETs', 'difficulty': 'applied', 'instruction': 'Explain this electronics concept to an undergraduate student.', 'question': "What happens to a MOSFET's drain current if the drain-source voltage is increased well beyond the overdrive voltage while gate-source voltage stays fixed?", 'answer': 'Once the transistor is in saturation, further increases in drain-source voltage have only a small effect on drain current (due to channel-length modulation), so the current stays approximately constant rather than continuing to rise proportionally.'}

In [66]:
import torch

def calculate_test_loss(model, test_data, tokenizer, max_length=512):
    model.eval()

    total_loss = 0.0
    total_tokens = 0

    for sample in test_data:

        # Create the conversation WITHOUT the answer
        messages = [
            {
                "role": "system",
                "content": sample["instruction"]
            },
            {
                "role": "user",
                "content": sample["question"]
            }
        ]

        # Prompt ending at assistant generation
        prompt = tokenizer.apply_chat_template(
            messages,
            tokenize=False,
            add_generation_prompt=True
        )

        # Full conversation INCLUDING the correct answer
        full_messages = messages + [
            {
                "role": "assistant",
                "content": sample["answer"]
            }
        ]

        full_text = tokenizer.apply_chat_template(
            full_messages,
            tokenize=False,
            add_generation_prompt=False
        )

        # Tokenize prompt and full conversation
        prompt_tokens = tokenizer(
            prompt,
            return_tensors="pt",
            truncation=True,
            max_length=max_length
        )

        full_tokens = tokenizer(
            full_text,
            return_tensors="pt",
            truncation=True,
            max_length=max_length
        )

        input_ids = full_tokens["input_ids"].to(model.device)
        attention_mask = full_tokens["attention_mask"].to(model.device)

        # Labels start as -100, meaning "don't calculate loss"
        labels = input_ids.clone()

        # Ignore everything belonging to system + user prompt
        prompt_length = prompt_tokens["input_ids"].shape[1]

        labels[:, :prompt_length] = -100

        with torch.no_grad():
            outputs = model(
                input_ids=input_ids,
                attention_mask=attention_mask,
                labels=labels
            )

        # Count actual answer tokens
        num_answer_tokens = (labels != -100).sum().item()

        total_loss += outputs.loss.item() * num_answer_tokens
        total_tokens += num_answer_tokens

    return total_loss / total_tokens

In [78]:
lora_fine_tuned_loss = calculate_test_loss(
    model,
    test,
    tokenizer
)

print("Fine-tuned model loss:", lora_fine_tuned_loss)

Fine-tuned model loss: 1.6571453626025212

In [79]:
base_loss = calculate_test_loss(
    base_model,
    test,
    base_tokenizer
)

print("Base model loss:", base_loss)

Base model loss: 2.113218175221796

In [81]:
print(f"Base model loss:       {base_loss:.4f}")
print(f"Fine-tuned model loss: {lora_fine_tuned_loss:.4f}")
print(f"Loss reduction:        {base_loss - lora_fine_tuned_loss:.4f}")

Base model loss:       2.1132
Fine-tuned model loss: 1.6571
Loss reduction:        0.4561

Training:
3 epochs

Trainable parameters:
1,089,536 / 1,544,803,840
= 0.0705%

Validation loss:
1.5563

Test loss:
Base model       = 2.1132
Fine-tuned model = 1.6593

Test loss reduction:
21.5%

QLoRA Section

In [70]:
!pip install -U bitsandbytes
!pip install -U bitsandbytes>=0.46.1

Requirement already satisfied: bitsandbytes in /usr/local/lib/python3.12/dist-packages (0.50.1)
Requirement already satisfied: torch<3,>=2.4 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes) (2.11.0+cu128)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes) (2.0.2)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes) (26.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.4->bitsandbytes) (3.29.7)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.4->bitsandbytes) (4.16.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.4->bitsandbytes) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.4->bitsandbytes) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.4->bitsandbytes) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.4->bitsandbytes) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.4->bitsandbytes) (2025.3.0)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<3,>=2.4->bitsandbytes) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.4->bitsandbytes) (12.9.7)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.4->bitsandbytes) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.4->bitsandbytes) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.4->bitsandbytes) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.4->bitsandbytes) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.4->bitsandbytes) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<3,>=2.4->bitsandbytes) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<3,>=2.4->bitsandbytes) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<3,>=2.4->bitsandbytes) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<3,>=2.4->bitsandbytes) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<3,>=2.4->bitsandbytes) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<3,>=2.4->bitsandbytes) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<3,>=2.4->bitsandbytes) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<3,>=2.4->bitsandbytes) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<3,>=2.4->bitsandbytes) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<3,>=2.4->bitsandbytes) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<3,>=2.4->bitsandbytes) (12.8.90)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings<13,>=12.9.4->torch<3,>=2.4->bitsandbytes) (1.5.6)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch<3,>=2.4->bitsandbytes) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch<3,>=2.4->bitsandbytes) (3.0.3)

In [71]:
from transformers import BitsAndBytesConfig
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer


checkpoint = "Qwen/Qwen2.5-1.5B-Instruct"


qlora_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type = "nf4",
    bnb_4bit_use_double_quant = True,
    bnb_4bit_compute_dtype=torch.bfloat16,
    device_map="auto"

)

qlora_model = AutoModelForCausalLM.from_pretrained(checkpoint,quantization_config = qlora_config)

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

In [72]:
from peft import prepare_model_for_kbit_training

qlora_model = prepare_model_for_kbit_training(qlora_model)

In [73]:
from peft import get_peft_model,LoraConfig

qlora_peft_config = LoraConfig(
    target_modules = ["q_proj","v_proj"],
    task_type = "CAUSAL_LM",
    r = 8,
    lora_alpha = 16,
    lora_dropout= 0.05
)

qlora_peft_model = get_peft_model(qlora_model,qlora_peft_config)
qlora_peft_model.print_trainable_parameters()

trainable params: 1,089,536 || all params: 1,544,803,840 || trainable%: 0.0705

In [74]:
from trl import SFTConfig,SFTTrainer

sft_config = SFTConfig(
    output_dir="./results",

    # Training
    num_train_epochs=3,
    per_device_train_batch_size=2,
    gradient_accumulation_steps=4,
    learning_rate=2e-4,

    # Sequence length
    max_length=512,

    # Evaluation
    eval_strategy="epoch",

    # Saving
    save_strategy="epoch",

    # Train only on assistant responses
    assistant_only_loss=True,

    # Optional
    logging_steps=10,
    report_to="none",
)

trainer = SFTTrainer(model=qlora_peft_model,args=sft_config,train_dataset=train_dataset,eval_dataset=valid_dataset)

trainer.train()

Tokenizing train dataset:   0%|          | 0/200 [00:00<?, ? examples/s]

Building labels for train dataset:   0%|          | 0/200 [00:00<?, ? examples/s]

Truncating train dataset:   0%|          | 0/200 [00:00<?, ? examples/s]

Dropping fully masked examples from train dataset:   0%|          | 0/200 [00:00<?, ? examples/s]

Tokenizing eval dataset:   0%|          | 0/25 [00:00<?, ? examples/s]

Building labels for eval dataset:   0%|          | 0/25 [00:00<?, ? examples/s]

Truncating eval dataset:   0%|          | 0/25 [00:00<?, ? examples/s]

Dropping fully masked examples from eval dataset:   0%|          | 0/25 [00:00<?, ? examples/s]

[transformers] The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None, 'pad_token_id': 151643}.

TrainOutput(global_step=75, training_loss=1.670069637298584, metrics={'train_runtime': 374.5413, 'train_samples_per_second': 1.602, 'train_steps_per_second': 0.2, 'total_flos': 486498617659392.0, 'train_loss': 1.670069637298584, 'epoch': 3.0})

In [75]:
inputs = tokenizer(prompt, return_tensors="pt").to(qlora_peft_model.device)

outputs = qlora_peft_model.generate(
    **inputs,
    max_new_tokens=256,
    do_sample=False
)

generated = tokenizer.decode(
    outputs[0][inputs["input_ids"].shape[1]:],
    skip_special_tokens=True
)

print("QLoRA MODEL ANSWER:")
print(generated)

print("\nREFERENCE ANSWER:")
print(reference_answer)

QLoRA MODEL ANSWER:
The drain current increases exponentially with increasing VDS, until it reaches saturation at some maximum value determined by the device's threshold voltage and channel length modulation effects.

REFERENCE ANSWER:
Once the transistor is in saturation, further increases in drain-source voltage have only a small effect on drain current (due to channel-length modulation), so the current stays approximately constant rather than continuing to rise proportionally.

In [82]:
qlora_fine_tuned_loss = calculate_test_loss(
    qlora_peft_model,
    test,
    tokenizer
)

print("Fine-tuned qlora-model loss:", qlora_fine_tuned_loss)

Fine-tuned qlora-model loss: 1.7316660406961017

In [83]:
import math

base_ppl = math.exp(base_loss)
lora_ppl = math.exp(lora_fine_tuned_loss)
qlora_ppl = math.exp(qlora_fine_tuned_loss)

print(f"Base Perplexity:  {base_ppl:.4f}")
print(f"LoRA Perplexity:  {lora_ppl:.4f}")
print(f"QLoRA Perplexity: {qlora_ppl:.4f}")

Base Perplexity:  8.2748
LoRA Perplexity:  5.2443
QLoRA Perplexity: 5.6501